import org.gradle.api.tasks.testing.Test
import org.gradle.api.tasks.Exec
import java.nio.charset.StandardCharsets

plugins {
    base
    alias(libs.plugins.spring.boot) apply false
    alias(libs.plugins.kotlin.jvm) apply false
    alias(libs.plugins.kotlin.spring) apply false
    alias(libs.plugins.spotless)
}

group = "io.github.fullstacknick.outboxer"
version = "1.0.0"

allprojects {
    group = rootProject.group
    version = rootProject.version
}

subprojects {
    val moduleName = name
    val internalGroup = rootProject.group.toString()
    val inventoryOutput = rootProject.layout.buildDirectory.file("reports/licenses/components/$moduleName.txt")

    configurations.configureEach {
        resolutionStrategy.activateDependencyLocking()
    }

    tasks.withType<Test>().configureEach {
        useJUnitPlatform()
        testLogging {
            events("failed", "skipped")
        }
    }

    tasks.register("dependencyInventory") {
        group = "verification"
        description = "Resolves this module's dependency coordinates for the root license report."
        doLast {
            val dependencies = sortedSetOf<String>()
            listOf("runtimeClasspath", "testRuntimeClasspath", "integrationTestRuntimeClasspath")
                .mapNotNull(configurations::findByName)
                .filter { it.isCanBeResolved }
                .forEach { configuration ->
                    configuration.incoming.resolutionResult.allComponents.forEach { component ->
                        component.moduleVersion
                            ?.takeUnless { module -> module.group == internalGroup }
                            ?.let { module -> dependencies += "${module.group}:${module.name}:${module.version}" }
                    }
                }
            val output = inventoryOutput.get().asFile
            output.parentFile.mkdirs()
            output.writeText(
                dependencies.joinToString(System.lineSeparator(), postfix = System.lineSeparator()),
                StandardCharsets.UTF_8,
            )
        }
    }
}

spotless {
    format("source") {
        target("**/*.java", "**/*.kt")
        targetExclude("**/build/**")
        trimTrailingWhitespace()
        endWithNewline()
    }
    format("repository") {
        target("*.kts", "*.md", "*.yml", "*.yaml", "*.json", "*.sh", "*.ps1")
        targetExclude(
            "INTERNAL_PROJECT_PLAN.md",
            "gradle/verification-metadata.xml",
            "docs/evidence/**",
        )
        trimTrailingWhitespace()
        endWithNewline()
    }
}

tasks.named("check") {
    dependsOn(subprojects.map { "${it.path}:check" })
    dependsOn("spotlessCheck")
}

tasks.register("integrationTest") {
    group = "verification"
    description = "Runs all component integration tests."
    dependsOn(":central-cycle-service:integrationTest")
}

tasks.register("contractCompatibilityTest") {
    group = "verification"
    description = "Runs the version 1 and version 2 contract compatibility suite."
    dependsOn(":contracts:test")
}

fun registerAcceptanceTask(name: String, mode: String, taskDescription: String) = tasks.register<Exec>(name) {
    group = "verification"
    description = taskDescription
    val javaBinary = file(
        "${System.getProperty("java.home")}/bin/java${if (System.getProperty("os.name").startsWith("Windows")) ".exe" else ""}",
    )
    workingDir(rootDir)
    commandLine(javaBinary, file("scripts/AcceptanceCoordinator.java"), mode)
}

registerAcceptanceTask("composeSmokeTest", "smoke", "Runs the local Docker Compose smoke test.").configure {
    dependsOn("check")
}

registerAcceptanceTask("crashWindowTest", "crash", "Runs deterministic edge and central crash-window tests.").configure {
    dependsOn("check")
}

registerAcceptanceTask("loadTest", "load", "Runs the sustained local throughput test.").configure {
    dependsOn("check")
}

registerAcceptanceTask("outageTest", "outage", "Runs the full local outage and recovery acceptance test.").configure {
    dependsOn("check")
}

tasks.register("licenseReport") {
    group = "verification"
    description = "Writes a deterministic inventory of resolved JVM dependencies and runtime images."
    dependsOn(subprojects.map { "${it.path}:dependencyInventory" })
    doLast {
        val dependencies = fileTree(layout.buildDirectory.dir("reports/licenses/components"))
            .matching { include("*.txt") }
            .files
            .flatMap { it.readLines(StandardCharsets.UTF_8) }
            .filter(String::isNotBlank)
            .toSortedSet()

        val output = layout.buildDirectory.file("reports/licenses/resolved-dependencies.txt").get().asFile
        output.parentFile.mkdirs()
        val lines = buildList {
            add("Outboxer resolved dependency inventory")
            add("Generated by: ./gradlew licenseReport")
            add("")
            add("JVM modules")
            addAll(dependencies)
            add("")
            add("Runtime container images")
            add("apache/kafka:4.3.1")
            add("eclipse-mosquitto:2.1.2-alpine")
            add("eclipse-temurin:21-jdk-jammy@sha256:ce5767b7222312d42395f5bab033cd91f09e44032a2f21bdfd7b5b912dbe1e77")
            add("eclipse-temurin:21-jre-jammy@sha256:eebd356ad7358b7094758e5787a6726f332917cfd56feab6457c56dab895cdbf")
            add("postgres:18.6-alpine")
        }
        output.writeText(lines.joinToString(System.lineSeparator(), postfix = System.lineSeparator()), StandardCharsets.UTF_8)
        logger.lifecycle("Dependency inventory written to ${output.relativeTo(rootDir)}")
    }
}

fun localScript(powerShellScript: String, bashScript: String, vararg arguments: String): List<String> {
    val windows = System.getProperty("os.name").startsWith("Windows")
    return if (windows) {
        listOf("pwsh", "-NoProfile", "-File", powerShellScript) + arguments
    } else {
        listOf("bash", bashScript) + arguments
    }
}

tasks.register<Exec>("kubernetesManifestTest") {
    group = "verification"
    description = "Validates Kubernetes manifests from a local schema cache without cluster discovery."
    workingDir(rootDir)
    commandLine(localScript("scripts/kind-smoke.ps1", "scripts/kind-smoke.sh", if (System.getProperty("os.name").startsWith("Windows")) "-OfflineOnly" else "--offline-only"))
}

tasks.register<Exec>("kindSmokeTest") {
    group = "verification"
    description = "Runs the isolated local kind deployment smoke test."
    dependsOn("check")
    workingDir(rootDir)
    commandLine(localScript("scripts/kind-smoke.ps1", "scripts/kind-smoke.sh"))
}

tasks.register<Exec>("publicationCheck") {
    group = "verification"
    description = "Checks tracked content, history, links, locks, and repository metadata before publication."
    dependsOn("check", "kubernetesManifestTest", "licenseReport")
    val javaBinary = file(
        "${System.getProperty("java.home")}/bin/java${if (System.getProperty("os.name").startsWith("Windows")) ".exe" else ""}",
    )
    workingDir(rootDir)
    commandLine(javaBinary, file("scripts/PublicationCheck.java"))
}
