apiVersion: v1
kind: Service
metadata:
  name: outboxer-edge
  namespace: outboxer
  labels:
    app.kubernetes.io/name: outboxer-edge
    app.kubernetes.io/part-of: outboxer
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: outboxer-edge
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
